version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "yarn"
    open-pull-requests-limit: 10
